import { PhaseContext, runPhase, getPipelineOverview } from './PhaseRunner';

/**
 * Indexer Phase
 * Creates final README with architecture overview and component links.
 */
export async function runIndexer(ctx: PhaseContext): Promise<void> {
    await runPhase(
        'Indexer',
        'Create README and Sidebar',
        `# Indexer Agent

## Role
- **Your Stage**: Indexer (Final Stage)
- **Core Responsibility**: Create a high-quality README that serves as the definitive entry point for understanding this codebase
- **Critical Success Factor**: The README should answer "What is this? How is it organized? Where do I start?" within the first screen

## Input
- Read \`${ctx.intermediateDir}/L4/overview.md\`
- Read \`${ctx.intermediateDir}/L4/relationships.md\`
- **Read \`${ctx.intermediateDir}/L5/page_structure.json\`** - This defines the EXACT pages and their components
- Scan \`${ctx.outputPath}/pages/\`

## Workflow
Create \`${ctx.outputPath}/README.md\` with the following CONTENT sections (in order):

### 0. Disclaimer (at the very top)
Add this exact text at the very beginning of the README:
> **Note**: This documentation was auto-generated by an LLM. While we strive for accuracy, please refer to the source code for authoritative information.

### 1. Architecture Overview

**A. One-Line Summary**
Summarize the ENTIRE system in ONE sentence.

**B. System Context (C4Context diagram) - REQUIRED**
Show how this system fits in the bigger picture:
- Write 2-3 sentences explaining the system context BEFORE the diagram
- Use \`C4Context\` Mermaid diagram
- Show: external systems/users, system boundaries
- Keep it high-level (5-7 nodes max)

**C. Core State Transitions (stateDiagram-v2) - REQUIRED**
Show the fundamental state machine of the system:
- Write 2-3 sentences explaining the state flow BEFORE the diagram
- Use \`stateDiagram-v2\` Mermaid diagram
- Show: main states, what triggers transitions
- Focus on the CORE flow, not edge cases

**D. Component Overview (block) - REQUIRED**
**CRITICAL: Use page_structure.json as the source of truth.**
- The block diagram MUST match EXACTLY the pages listed in \`${ctx.intermediateDir}/L5/page_structure.json\`
- Each block in the diagram = one page from page_structure.json
- Write 2-3 sentences explaining the component structure BEFORE the diagram
- Use \`block\` Mermaid diagram
- **Nesting rules**: One level of nesting is OK (box inside box for grouping). Deeper nesting (box inside box inside box) is FORBIDDEN.
- **Arrows (-->) are forbidden** in block diagrams
- This should serve as a VISUAL TABLE OF CONTENTS that matches the Components section

### 2. Components
**CRITICAL: Use page_structure.json as the source of truth.**
For EACH page in \`${ctx.intermediateDir}/L5/page_structure.json\`:
- **Name** with link to its page: [PageName](pages/PageName.md)
- **One-line description** of what it covers (use the rationale from page_structure.json)

## Output
- Write README.md to \`${ctx.outputPath}/README.md\`

## Constraints
1. **Scope**: Do NOT Modify files outside of the ".deepwiki" directory. Read-only access is allowed for source code.
2. **Chat Final Response**: Keep your chat reply brief (e.g., "Task completed."). Do not include file contents in your response.
3. **Incremental Writing**: You have a limited token budget. Write incrementally.
   - Do NOT: Analyze all items then write all at end
   - DO: Analyze one item, write immediately, then move to next
   - Create file with first section, then use \`applyPatch\` to write each section IMMEDIATELY after analyzing it.
4. **Sanitize Intermediate Links**: REMOVE or REWRITE any references to intermediate directory files (e.g., intermediate/, ../L3/, ../L4/). Only include links to final pages in the \`pages/\` directory.
5. **Synthesize, Don't Dump**: Do NOT just copy L4 Overview - synthesize it into the sections above.
6. **Required Diagrams**: All 3 diagrams (C4Context, stateDiagram, block) are REQUIRED.

` + getPipelineOverview('Indexer'),
        ctx
    );
}
